import { useState } from 'react'
import { FileCode, Copy, Check } from 'lucide-react'

const LEGACY_JS = `// ❌ BEFORE — LegacyWidget.js (plain JavaScript)
function LegacyWidget(props) {
  const [data, setData] = useState(null)  // no types
  const intervalRef = useRef(null)         // missing generic

  useEffect(() => {
    intervalRef.current = setInterval(     // ❌ memory leak
      () => fetchData(props.userId), 5000  //    no cleanup
    )
  }, [])

  function fetchData(userId) {             // no type annotations
    fetch('/api/users/' + userId)
      .then(res => res.json())
      .then(json => setData(json))
  }
  ...
}

LegacyWidget.propTypes = {               // propTypes instead
  userId: PropTypes.number.isRequired,   // of TS interfaces
  onSelect: PropTypes.func.isRequired,
}`

const MESSY_TS = `// ❌ BEFORE — MessyComponent.tsx (TypeScript with violations)
interface MessyProps {
  data: any          // ❌ no-any
  onSubmit: any      // ❌ no-any
  config: any        // ❌ no-any
}

function MessyComponent(props: MessyProps) {
  const [state, setS] = useState<any>({})     // ❌ no-any
  const ref = useRef(null)                    // ❌ missing generic
                                              //    should be useRef<HTMLInputElement>(null)
  function process(item: any) {
    return (item as { name: string }).name    // ❌ unsafe cast
    // should use a type guard function
  }

  const handle = (e: any) => { ... }         // ❌ no-any
}`

const GENERATED = `// ✅ AFTER — Button.tsx (generated by component-factory)
import type { ButtonHTMLAttributes } from 'react'
import { forwardRef } from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@repo/ui/utils'

const buttonVariants = cva(
  'inline-flex items-center justify-center rounded-md text-sm font-medium',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        outline: 'border border-input hover:bg-accent',
        ghost:   'hover:bg-accent hover:text-accent-foreground',
      },
      size: {
        sm: 'h-9 px-3',
        md: 'h-10 px-4',
        lg: 'h-11 px-8',
      },
    },
    defaultVariants: { variant: 'default', size: 'md' },
  }
) as const  // ✅ const assertion

interface ButtonProps
  extends ButtonHTMLAttributes<HTMLButtonElement>,  // ✅ typed
    VariantProps<typeof buttonVariants> {
  readonly asChild?: boolean   // ✅ readonly modifier
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(  // ✅ generic
  ({ className, variant, size, ...props }, ref) => (
    <button
      ref={ref}
      className={cn(buttonVariants({ variant, size }), className)}
      aria-disabled={props.disabled}   // ✅ accessibility
      {...props}
    />
  )
)
Button.displayName = 'Button'
export { Button, buttonVariants }`

type PanelTab = 'legacy-js' | 'messy-ts' | 'generated'

const tabs: { id: PanelTab; label: string; badge: string; badgeColor: string }[] = [
  { id: 'legacy-js', label: 'LegacyWidget.js', badge: 'JS', badgeColor: 'bg-yellow-900 text-yellow-300' },
  { id: 'messy-ts', label: 'MessyComponent.tsx', badge: 'TS violations', badgeColor: 'bg-red-900 text-red-300' },
  { id: 'generated', label: 'Button.tsx', badge: 'generated', badgeColor: 'bg-emerald-900 text-emerald-300' },
]

const code: Record<PanelTab, string> = {
  'legacy-js': LEGACY_JS,
  'messy-ts': MESSY_TS,
  'generated': GENERATED,
}

export function CodePanel() {
  const [activeTab, setActiveTab] = useState<PanelTab>('legacy-js')
  const [copied, setCopied] = useState(false)

  const copy = () => {
    navigator.clipboard.writeText(code[activeTab])
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div className="flex flex-col h-full bg-zinc-950 rounded-lg border border-zinc-800 overflow-hidden">
      {/* Header */}
      <div className="flex items-center gap-2 px-3 py-2 border-b border-zinc-800 shrink-0">
        <FileCode className="w-4 h-4 text-zinc-500" />
        <span className="text-xs text-zinc-500 font-medium">Source Files</span>
        <button
          onClick={copy}
          className="ml-auto p-1 rounded hover:bg-zinc-800 text-zinc-600 hover:text-zinc-300 transition-colors"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-zinc-800 shrink-0 overflow-x-auto">
        {tabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex items-center gap-1.5 px-3 py-2 text-xs font-mono whitespace-nowrap transition-colors ${
              activeTab === tab.id
                ? 'text-white border-b-2 border-blue-500 bg-zinc-900'
                : 'text-zinc-500 hover:text-zinc-300'
            }`}
          >
            {tab.label}
            <span className={`px-1 py-0.5 rounded text-[10px] ${tab.badgeColor}`}>
              {tab.badge}
            </span>
          </button>
        ))}
      </div>

      {/* Code */}
      <pre className="flex-1 p-4 text-xs font-mono text-zinc-300 overflow-auto leading-relaxed">
        <code>{code[activeTab]}</code>
      </pre>
    </div>
  )
}
