import { defineConfig } from 'tsup'

export default defineConfig({
  entry: [
    'src/index.ts',
    'components/Accordion/index.ts',
    'components/Alert/index.ts',
    'components/AspectRatio/index.ts',
    'components/AutoForm/index.ts',
    'components/Avatar/index.ts',
    'components/Badge/index.ts',
    'components/Breadcrumb/index.ts',
    'components/Button/index.ts',
    'components/Calendar/index.ts',
    'components/Card/index.ts',
    'components/Checkbox/index.ts',
    'components/Collapsible/index.ts',
    'components/Command/index.ts',
    'components/ContextMenu/index.ts',
    'components/DataTable/index.ts',
    'components/Dialog/index.ts',
    'components/Drawer/index.ts',
    'components/DropdownMenu/index.ts',
    'components/Form/index.ts',
    'components/HoverCard/index.ts',
    'components/Input/index.ts',
    'components/InputOTP/index.ts',
    'components/Label/index.ts',
    'components/Menubar/index.ts',
    'components/NavigationMenu/index.ts',
    'components/Pagination/index.ts',
    'components/Popover/index.ts',
    'components/Progress/index.ts',
    'components/RadioGroup/index.ts',
    'components/ScrollArea/index.ts',
    'components/Select/index.ts',
    'components/Separator/index.ts',
    'components/Sheet/index.ts',
    'components/Skeleton/index.ts',
    'components/Slider/index.ts',
    'components/Sonner/index.ts',
    'components/Switch/index.ts',
    'components/Table/index.ts',
    'components/Tabs/index.ts',
    'components/Textarea/index.ts',
    'components/Toggle/index.ts',
    'components/ToggleGroup/index.ts',
    'components/Tooltip/index.ts',
  ],
  format: ['esm', 'cjs'],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  treeshake: true,
  external: ['react', 'react-dom'],
  esbuildOptions(options) {
    options.jsx = 'automatic'
  },
})
