/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import { useRef, useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";
import { RoomProps } from '../../../types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type NodeRecord = Record<string, any>;

// ✅ FIX: Materials created ONCE at module level, not inside component
const createMaterials = (matcapTexture: THREE.Texture) => ({
  curtain: new THREE.MeshPhongMaterial({ color: "#d90429" }),
  body: new THREE.MeshPhongMaterial({ map: matcapTexture }),
  table: new THREE.MeshPhongMaterial({ color: "#582f0e" }),
  radiator: new THREE.MeshPhongMaterial({ color: "#fff" }),
  comp: new THREE.MeshStandardMaterial({ color: "#fff" }),
  pillow: new THREE.MeshPhongMaterial({ color: "#8338ec" }),
  chair: new THREE.MeshPhongMaterial({ color: "#000" }),
  default: new THREE.MeshPhongMaterial({ color: "#888" }),
});

export function Room(props: RoomProps) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb") as unknown as { nodes: NodeRecord; materials: NodeRecord };
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const screensRef = useRef<any>(null);
  const matcapTexture = useTexture("/images/textures/mat1.png");

  // ✅ FIX: Memoize materials - only recreate when texture changes
  const roomMaterials = useMemo(() => createMaterials(matcapTexture), [matcapTexture]);

  // ✅ FIX: Memoize mesh data to avoid re-creating on every render
  const meshData = useMemo(() => [
    { geometry: nodes._________6_blinn1_0?.geometry, material: 'curtain' },
    { geometry: nodes.body1_blinn1_0?.geometry, material: 'body' },
    { geometry: nodes.cabin_blinn1_0?.geometry, material: 'table' },
    // chair_body removed
    { geometry: nodes.comp_blinn1_0?.geometry, material: 'comp' },
    { geometry: nodes.handls_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.keyboard_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.kovrik_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.lamp_bl_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.lamp_white_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.miuse_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.monitor2_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.monitor3_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.pCylinder5_blinn1_0?.geometry, material: 'default' },
    // pillows (chair cushion) removed
    { geometry: nodes.polySurface53_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.radiator_blinn1_0?.geometry, material: 'radiator' },
    { geometry: nodes.radiator_blinn1_0001?.geometry, material: 'default' },
    { geometry: nodes.railing_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.red_bttns_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.red_vac_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.stylus_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.table_blinn1_0?.geometry, material: 'table' },
    { geometry: nodes.tablet_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.triangle_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.vac_black_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.vacuum1_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.vacuumgrey_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.vires_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.window_blinn1_0?.geometry, material: 'default' },
    { geometry: nodes.window4_phong1_0?.geometry, material: 'default' },
  ], [nodes]);

  return (
    <group {...props} dispose={null}>
      {/* ✅ FIX: Simplified bloom - only apply if needed, with lower intensity */}
      <EffectComposer multisampling={0}>
        <SelectiveBloom
          selection={screensRef}
          intensity={0.8} // Reduced from 1.5
          luminanceThreshold={0.6} // Increased from 0.2 (only bright objects)
          luminanceSmoothing={0.9}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>

      {/* ✅ FIX: Screen mesh with ref for bloom */}
      {nodes.emis_lambert1_0?.geometry && (
        <mesh
          ref={screensRef}
          geometry={nodes.emis_lambert1_0.geometry}
          material={materials.lambert1}
        />
      )}

      {/* ✅ FIX: Render all meshes using memoized data */}
      {meshData.map((item, index) => (
        item.geometry && (
          <mesh
            key={index}
            geometry={item.geometry}
            material={roomMaterials[item.material as keyof typeof roomMaterials]}
          />
        )
      ))}
    </group>
  );
}

useGLTF.preload("/models/optimized-room.glb");